Repository stolostron/multicloud-integrations, pull requests merged in 2025-06, with the labels that each got.

#327 Join errors together when adding managed cluster secrets for GitOpsCluster
  e2e/run_e2e.sh
  pkg/controller/gitopscluster/gitopscluster_controller.go
  pkg/controller/gitopscluster/gitopscluster_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#334 ArgoCD pull model with maestro integration
  Makefile
  Makefile.prow
  build/Dockerfile
  build/Dockerfile.prow
  build/Dockerfile.rhtap
  cmd/maestroaggregation/main.go
  cmd/maestropropagation/main.go
  gitopsaddon/addonTemplates/addonTemplates.yaml
  gitopsaddon/charts/openshift-gitops-dependency/Chart.yaml
  gitopsaddon/charts/openshift-gitops-operator/templates/crds/applications.argoproj.io.crd.yaml
  gitopsaddon/charts/openshift-gitops-operator/templates/crds/argocd.crd.yaml
  go.mod
  go.sum
  maestroapplication/README.md
  maestroapplication/aggregation_controller.go
  maestroapplication/charts/multicluster-maestro-integrations/Chart.yaml
  maestroapplication/charts/multicluster-maestro-integrations/templates/multicluster-maestro-integrations.deployment.yaml
  maestroapplication/charts/multicluster-maestro-integrations/values.yaml
  maestroapplication/examples/gitopscluster-all-clusters.yaml
  maestroapplication/examples/pull-model-appset-bgdk.yaml
  maestroapplication/maestro_helper.go
  maestroapplication/propagation_controller.go
  pkg/controller/gitopscluster/gitopscluster_controller.go
Labels: approved, dco-signoff: yes

#335 update konfluxFix references
  .tekton/multicloud-integrations-acm-214-pull-request.yaml
  .tekton/multicloud-integrations-acm-214-push.yaml
Labels: approved, dco-signoff: yes, do-not-merge/hold
