Repository stolostron/multicloud-integrations, pull requests merged in 2025-09, with the labels that each got.

#386 feat: add argocd-agent deploy to the gitops-addon
  Makefile
  Makefile.prow
  cmd/gitopsaddon/main.go
  cmd/gitopsaddon/main_test.go
  cmd/gitopscluster/exec/manager.go
  cmd/gitopscluster/exec/manager_test.go
  common/config/.golangci.yml
  deploy/controller/role.yaml
  deploy/crds/apps.open-cluster-management.io_gitopsclusters.yaml
  deploy/ocm/install.sh
  e2e/hub/agent-principal.yaml
  e2e/hub/dummy-application-svc-ca-secret.yaml
  e2e/run_e2e.sh
  examples/argocd/README.md
  examples/argocd/gitopscluster-with-agent.yaml
  examples/gitopscluster.yaml
  gitopsaddon/addonTemplates/addonDeploymentConfig.yaml
  gitopsaddon/addonTemplates/addonTemplates.yaml
  gitopsaddon/addonTemplates/clusterManagementAddon.yaml
  gitopsaddon/addonTemplates/managedClusterAddon.yaml
  gitopsaddon/charts/argocd-agent/Chart.yaml
  gitopsaddon/charts/argocd-agent/templates/agent-clusterrole.yaml
  gitopsaddon/charts/argocd-agent/templates/agent-clusterrolebinding.yaml
  gitopsaddon/charts/argocd-agent/templates/agent-deployment.yaml
  gitopsaddon/charts/argocd-agent/templates/agent-healthz-service.yaml
  gitopsaddon/charts/argocd-agent/templates/agent-metrics-service.yaml
  gitopsaddon/charts/argocd-agent/templates/agent-params-cm.yaml
  gitopsaddon/charts/argocd-agent/templates/agent-role.yaml
  gitopsaddon/charts/argocd-agent/templates/agent-rolebinding.yaml
  gitopsaddon/charts/argocd-agent/templates/agent-sa.yaml
  gitopsaddon/charts/argocd-agent/values.yaml
  gitopsaddon/charts/openshift-gitops-operator/templates/argocd-operator-manager-role.clusterrole.yaml
  gitopsaddon/gitopsaddon_controller.go
  gitopsaddon/gitopsaddon_controller_argocd_test.go
  gitopsaddon/gitopsaddon_controller_test.go
  gitopsaddon/secret_controller.go
  gitopsaddon/secret_controller_test.go
  maestroapplication/charts/multicluster-maestro-integrations/values.yaml
  pkg/apis/apps/v1beta1/gitopscluster_types.go
  pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
  pkg/controller/gitopscluster/argocd_agent_certificates.go
  pkg/controller/gitopscluster/argocd_agent_certificates_test.go
  pkg/controller/gitopscluster/argocd_agent_test.go
  pkg/controller/gitopscluster/gitopscluster_controller.go
  pkg/controller/gitopscluster/gitopscluster_controller_suite_test.go
  pkg/controller/gitopscluster/gitopscluster_controller_test.go
Labels: approved, dco-signoff: yes

#394 release-2.13 - konflux
  .tekton/multicloud-integrations-acm-213-pull-request.yaml
  .tekton/multicloud-integrations-acm-213-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#395 release-2.14 - konflux
  .tekton/multicloud-integrations-acm-214-pull-request.yaml
  .tekton/multicloud-integrations-acm-214-push.yaml
Labels: lgtm, approved, dco-signoff: yes

#392 release-2.11 - konflux
  .tekton/multicloud-integrations-acm-211-pull-request.yaml
  .tekton/multicloud-integrations-acm-211-push.yaml
  build/Dockerfile.rhtap
  rpms.in.yaml
  rpms.lock.yaml
Labels: lgtm, approved, dco-signoff: yes

#403 Add CLAUDE.md documentation
  CLAUDE.md
Labels: dco-signoff: no, needs-ok-to-test

#405 feat: add JWT secret creation for ArgoCD agent prerequisites
  e2e-gitopsaddon/openshift-gitops/operator-instance.yaml
  pkg/apis/apps/v1beta1/gitopscluster_test.go
  pkg/apis/apps/v1beta1/gitopscluster_types.go
  pkg/apis/apps/v1beta1/gitopscluster_types_unit_test.go
  pkg/controller/gitopscluster/gitopscluster_controller.go
  pkg/controller/gitopscluster/gitopscluster_controller_test.go
  pkg/controller/gitopscluster/secret_management.go
  pkg/controller/gitopscluster/secret_management_test.go
Labels: approved, dco-signoff: yes

#408 refactor: improve gitopscluster controller readability and fix createBlankClusterSecrets logic
  pkg/controller/gitopscluster/gitopscluster_controller.go
  pkg/controller/gitopscluster/gitopscluster_controller_test.go
  pkg/controller/gitopscluster/import_clusters.go
  pkg/controller/gitopscluster/import_clusters_test.go
  pkg/controller/gitopscluster/policy_template.go
  pkg/controller/gitopscluster/policy_template_test.go
Labels: approved, dco-signoff: yes

#413 Refactor gitops addon controller: remove helm operations, add cleanup mechanism, and improve code structure
  cmd/gitopsaddon/main.go
  cmd/gitopsaddon/main_test.go
  deploy/crds/apps.open-cluster-management.io_gitopsclusters.yaml
  e2e-gitopsaddon/argocd.yaml
  e2e-gitopsaddon/argocdexportcrd.yaml
  e2e-gitopsaddon/gitopscluster/gitopscluster.yaml
  e2e-gitopsaddon/run_e2e-gitopsaddon.sh
  examples/gitopscluster-agent.yaml
  examples/gitopscluster.yaml
  gitopsaddon/addonTemplates/addonTemplates.yaml
  gitopsaddon/addonTemplates/example_addonDeploymentConfig.yaml
  gitopsaddon/charts/openshift-gitops-operator/templates/argocd-operator-controller-manager.deployment.yaml
  gitopsaddon/gitopsaddon_cleanup.go
  gitopsaddon/gitopsaddon_cleanup_test.go
  gitopsaddon/gitopsaddon_controller.go
  gitopsaddon/gitopsaddon_controller_argocd_test.go
  gitopsaddon/gitopsaddon_controller_suite_test.go
  gitopsaddon/gitopsaddon_controller_test.go
  gitopsaddon/gitopsaddon_controller_unit_test.go
  gitopsaddon/gitopsaddon_install.go
  gitopsaddon/gitopsaddon_install_test.go
  gitopsaddon/gitopsaddon_management_test.go
  gitopsaddon/gitopsaddon_test_setup.go
  gitopsaddon/gitopsaddon_utils.go
  gitopsaddon/gitopsaddon_utils_test.go
  pkg/apis/apps/v1beta1/gitopscluster_types.go
  pkg/apis/apps/v1beta1/gitopscluster_types_unit_test.go
  pkg/apis/apps/v1beta1/zz_generated.deepcopy.go
  pkg/controller/gitopscluster/addon_management.go
  pkg/controller/gitopscluster/addon_management_test.go
  pkg/controller/gitopscluster/gitopscluster_controller.go
  pkg/controller/gitopscluster/gitopscluster_controller_test.go
Labels: lgtm, approved, dco-signoff: yes

#414 fix: restore original behavior after import_clusters refactoring
  pkg/controller/gitopscluster/gitopscluster_controller_test.go
  pkg/controller/gitopscluster/import_clusters.go
  pkg/controller/gitopscluster/import_clusters_test.go
Labels: lgtm, approved, dco-signoff: yes

#416 disable automatically set OverrideExistingConfigs to true when uninstall is true
  e2e-gitopsaddon/run_e2e-gitopsaddon.sh
  pkg/controller/gitopscluster/addon_management.go
Labels: lgtm, approved, dco-signoff: yes
